# BCI Competition IV Dataset
<p>
Information Given in Documentation

From the documentation it is known that:
<li>25 electrodes are used, first 22 are EEG, last 3 are EOG
<li>Sampling frequency (fs) is 250Hz
<li>9 subjects
<li>9 run (run 1-3 are for eye movement, run 4-9 is MI)

<b> -- Time Duration-- </b>

1 trials                          = 7-8s
1 run              = 48 trials    = 336-384s
1 session = 6 runs = 288 trials   = 2016-2304s

About the recording of eye movement
<li>run 1 => 2 mins with eyes open
<li>run 2 => 1 min with eyes closed
<li>run 3 => 1 min with eye movements

## Visualizing/ Preparing the Data 

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.io as io
import pandas as pd
from pandas import DataFrame as df

In [6]:
np.seterr(divide='ignore', invalid='ignore')

{'divide': 'ignore', 'over': 'warn', 'under': 'ignore', 'invalid': 'ignore'}

In [7]:
np.set_printoptions(precision=4, suppress=True)

In [8]:
 # Load the training data of subject 01
data = io.loadmat('./datasets/A03T.mat')

In [9]:
type(data)

dict

In [10]:
data.keys()

dict_keys(['__header__', '__version__', '__globals__', 'data'])

In [11]:
# Store each datasets(X) into variable, each variable contains i th run for 1st subject
EEG_data04 = data['data'][0,3]['X'][0, 0] # Take 1 run from total 6 runs (4th run)
EEG_data05 = data['data'][0,4]['X'][0, 0] # Take 1 run from total 6 runs (5th run)
EEG_data06 = data['data'][0,5]['X'][0, 0] # Take 1 run from total 6 runs (6th run)
EEG_data07 = data['data'][0,6]['X'][0, 0] # Take 1 run from total 6 runs (7th run)
EEG_data08 = data['data'][0,7]['X'][0, 0] # Take 1 run from total 6 runs (8th run)
EEG_data09 = data['data'][0,8]['X'][0, 0] # Take 1 run from total 6 runs (9th run)

In [12]:
# Store each label(y) into variable, each variable contain i th label correspons to 48 trial of each run
y04 = data['data'][0,3]['y'][0, 0].flatten() # Take y data corresponds to 48 trials in 4th run
y05 = data['data'][0,4]['y'][0, 0].flatten() # Take y data corresponds to 48 trials in 5th run
y06 = data['data'][0,5]['y'][0, 0].flatten() # Take y data corresponds to 48 trials in 6th run
y07 = data['data'][0,6]['y'][0, 0].flatten() # Take y data corresponds to 48 trials in 7th run
y08 = data['data'][0,7]['y'][0, 0].flatten() # Take y data corresponds to 48 trials in 8th run
y09 = data['data'][0,8]['y'][0, 0].flatten() # Take y data corresponds to 48 trials in 9th run

In [13]:
y04

array([1, 2, 2, 1, 2, 1, 2, 3, 2, 4, 1, 3, 2, 1, 4, 4, 4, 4, 4, 1, 3, 2,
       1, 1, 3, 4, 1, 3, 3, 3, 1, 2, 1, 2, 2, 1, 2, 3, 2, 3, 3, 4, 3, 3,
       4, 4, 4, 4], dtype=uint8)

In [14]:
# Removing last 3 electrodes from EEG_data since they are EOG
EEG_data04 = EEG_data04[:, :22]
EEG_data05 = EEG_data05[:, :22]
EEG_data06 = EEG_data06[:, :22]
EEG_data07 = EEG_data07[:, :22]
EEG_data08 = EEG_data08[:, :22]
EEG_data09 = EEG_data09[:, :22]

In [15]:
# Creating columns for X datasets
Xcol = []
for i in range(1, 23):
    if i < 11:
        Xcol.append('EEG0'+str(i))
    else:
        Xcol.append('EEG0'+str(i))

In [16]:
# Visualizing the dataset of X
dataX04 = pd.DataFrame(EEG_data09, columns=Xcol)
dataX04

EEG01      EEG02      EEG03      EEG04      EEG05      EEG06  \
0     -14.111328 -10.888672 -14.404297 -13.671875 -14.306641 -11.132812   
1       8.544922  12.646484   6.738281   9.472656   9.326172  17.675781   
2      -8.984375  -1.025391  -8.984375 -11.865234 -13.330078 -12.451172   
3     -13.134766 -14.794922 -18.701172 -14.697266 -15.234375  -5.322266   
4      -1.269531  -0.048828  -3.906250  -3.027344  -5.224609  -6.347656   
...          ...        ...        ...        ...        ...        ...   
96730  -7.226562   3.222656  -5.371094  -7.031250  -9.912109 -11.621094   
96731   6.591797   7.812500   4.785156   5.468750   2.050781   2.197266   
96732   9.765625  14.355469  10.351562   5.908203   6.933594   8.593750   
96733   8.544922   8.496094   5.615234   5.957031   7.177734   9.619141   
96734  22.167969  22.265625  17.822266  20.263672  19.970703  23.388672   

           EEG07      EEG08      EEG09     EEG010  ...     EEG013     EEG014  \
0      -8.935547  -9.423828 -12.695312 -16.894531  ... -24.804688  -9.179688   
1       8.544922  11.816406   7.470703   5.419922  ...  10.205078  10.693359   
2       3.076172  -3.222656  -8.886719 -16.015625  ... -13.671875  -7.275391   
3     -15.039062 -14.501953 -17.871094 -18.945312  ...  -3.466797 -14.501953   
4       5.029297   1.123047  -2.783203  -3.955078  ...  -6.152344   1.513672   
...          ...        ...        ...        ...  ...        ...        ...   
96730  -3.222656   2.685547  -1.367188  -6.738281  ...  -9.619141   3.027344   
96731  -5.566406  10.107422   8.105469   4.541016  ...   2.050781  11.474609   
96732  20.507812  14.208984  13.037109   5.175781  ...  10.156250  11.669922   
96733   8.203125   9.472656   9.326172   5.322266  ...  12.500000  11.035156   
96734  20.898438  22.851562  21.728516  19.873047  ...  20.019531  23.242188   

          EEG015     EEG016     EEG017     EEG018     EEG019     EEG020  \
0     -12.158203 -15.332031 -18.701172 -21.777344 -13.574219 -18.310547   
1       7.666016   5.468750   5.615234   5.126953   8.056641   4.931641   
2      -8.837891 -14.404297 -16.357422 -18.017578 -11.132812 -15.185547   
3     -17.333984 -17.529297 -18.017578 -19.726562 -16.748047 -19.335938   
4      -1.416016  -1.611328  -6.347656  -8.300781  -4.589844  -6.738281   
...          ...        ...        ...        ...        ...        ...   
96730  -1.171875  -4.345703  -6.005859  -3.173828   2.685547  -1.269531   
96731   8.691406   6.250000   3.027344   3.320312  11.083984   7.861328   
96732  11.132812   6.787109   5.761719   6.298828   9.716797   7.714844   
96733  11.181641   8.203125   7.275391   9.619141   9.619141   8.789062   
96734  21.875000  22.265625  22.705078  25.048828  24.902344  24.658203   

          EEG021     EEG022  
0     -16.455078 -18.603516  
1       6.201172   3.710938  
2     -15.380859 -15.576172  
3     -19.091797 -20.507812  
4      -7.958984 -10.351562  
...          ...        ...  
96730  -0.341797   1.464844  
96731   8.398438   9.570312  
96732   8.740234   6.738281  
96733  12.060547   8.935547  
96734  27.880859  24.755859  

[96735 rows x 22 columns]

In [17]:
m, n = EEG_data04.shape
print('There are %d samples' %m )
print('There are %d electrodes' %n)

There are 96735 samples
There are 22 electrodes


In [18]:
# Visualizing the label of y
data_y04 = pd.DataFrame(y04, columns=['class'])
data_y04

class
0       1
1       2
2       2
3       1
4       2
5       1
6       2
7       3
8       2
9       4
10      1
11      3
12      2
13      1
14      4
15      4
16      4
17      4
18      4
19      1
20      3
21      2
22      1
23      1
24      3
25      4
26      1
27      3
28      3
29      3
30      1
31      2
32      1
33      2
34      2
35      1
36      2
37      3
38      2
39      3
40      3
41      4
42      3
43      3
44      4
45      4
46      4
47      4

## Clipping of EEG_data, fetch data correspond to MI task


    Assumption:

    The MI start at 2s -> 500th
    Recording last for 3s -> 1250 samples
    Each trial ends at 8-> 2000th
    e.g.:
    1st trial -> clip 500- 1250
    2nd trial -> clip 2500- 3250
    3rd trial -> clip 4500- 5250

In [19]:
EEG_data04.shape

(96735, 22)

In [20]:
# One trial last nth samples (x seconds)
# Fetch nth - nth samples  (MI task, x seconds)
ntrial = 48 # Number of trial
dur = 2000 # Duration of each trial
fs = 250 # Sampling frequency
t = 3 # Assume the recording last for exactly 3s in each trial
start = 499 # Start trimming at 500th sample
ending = 1249 # Ending of each MI recording
nsamp = 750 # Samples of MI task per trial to be trimmed
nel = 22 # Number of all electrodes (minuse EOG)

In [21]:
# Preparing array to store each run data
run04 = np.zeros((ntrial, nsamp, nel))
run05 = np.zeros((ntrial, nsamp, nel))
run06 = np.zeros((ntrial, nsamp, nel))
run07 = np.zeros((ntrial, nsamp, nel))
run08 = np.zeros((ntrial, nsamp, nel))
run09 = np.zeros((ntrial, nsamp, nel))

In [22]:
# Check shape of run
run04.shape

(48, 750, 22)

In [23]:
# Iter over each EEG_data and trimmed samples corresponds to MI task 
# Array will contain data of MI task in each run
for i in range(ntrial):
    temp = EEG_data04[(dur*i+start):(dur*i+ending),:]
    run04[i, :, :] = temp
    
for i in range(ntrial):
    temp = EEG_data05[(dur*i+start):(dur*i+ending),:]
    run05[i, :, :] = temp

for i in range(ntrial):
    temp = EEG_data06[(dur*i+start):(dur*i+ending),:]
    run06[i, :, :] = temp

for i in range(ntrial):
    temp = EEG_data07[(dur*i+start):(dur*i+ending),:]
    run07[i, :, :] = temp

for i in range(ntrial):
    temp = EEG_data08[(dur*i+start):(dur*i+ending),:]
    run08[i, :, :] = temp

for i in range(ntrial):
    temp = EEG_data09[(dur*i+start):(dur*i+ending),:]
    run09[i, :, :] = temp

In [24]:
run08.shape

(48, 750, 22)

In [25]:
# Visualizing data of run 09 trial 19
pd.DataFrame(run09[39], columns=Xcol)

EEG01      EEG02      EEG03      EEG04      EEG05      EEG06  \
0     5.664062   8.544922   8.544922   9.179688   8.300781   9.472656   
1    -1.123047  -3.222656   0.781250  -2.783203  -1.953125  -5.664062   
2   -18.261719 -17.822266 -15.332031 -18.798828 -19.189453 -23.388672   
3     0.537109   9.667969   6.933594   5.664062   0.292969  -1.416016   
4     4.785156  12.841797  12.744141   8.447266   5.224609   1.220703   
..         ...        ...        ...        ...        ...        ...   
745  15.917969  18.945312  17.236328  16.601562  15.380859  17.431641   
746  26.464844  24.511719  25.585938  22.021484  25.000000  25.830078   
747   6.103516   9.033203   4.345703   6.298828   6.542969  17.138672   
748   9.863281  10.058594  10.498047   6.591797  10.253906  15.625000   
749   2.832031   2.783203   1.953125  -0.097656   2.636719   3.613281   

         EEG07      EEG08      EEG09     EEG010  ...     EEG013     EEG014  \
0    12.500000   9.570312   7.031250  11.376953  ...  17.919922   7.177734   
1    -0.537109  -3.808594  -1.513672  -1.757812  ... -15.234375  -6.982422   
2   -17.968750 -19.189453 -17.431641 -18.310547  ... -33.349609 -23.632812   
3     3.222656   6.835938   4.638672   6.787109  ... -10.400391   1.953125   
4     9.082031  10.595703  10.791016   8.984375  ...  -5.468750   7.128906   
..         ...        ...        ...        ...  ...        ...        ...   
745  24.365234  19.873047  15.234375  15.722656  ...   7.128906  17.675781   
746  23.437500  22.265625  22.167969  20.068359  ...  26.562500  20.263672   
747   5.468750   6.298828   2.197266   4.492188  ...  20.117188   5.419922   
748  10.009766   6.494141   6.542969   5.224609  ...  24.609375   4.882812   
749   3.417969  -0.341797  -0.976562  -0.634766  ...   7.910156  -0.781250   

        EEG015     EEG016     EEG017     EEG018     EEG019     EEG020  \
0     6.982422  10.253906   9.667969   8.544922   8.593750  10.595703   
1    -3.222656  -4.101562  -6.103516 -11.962891  -8.642578  -4.736328   
2   -20.068359 -22.119141 -24.609375 -31.347656 -27.050781 -24.658203   
3     1.708984   2.392578  -2.343750  -7.958984  -4.589844  -3.515625   
4     7.421875   4.541016  -0.976562  -7.275391  -4.101562  -3.613281   
..         ...        ...        ...        ...        ...        ...   
745  14.697266  13.134766  12.304688   9.033203  14.746094  11.279297   
746  22.265625  18.701172  21.533203  22.265625  20.507812  19.189453   
747   3.027344   5.468750   7.421875  10.693359   5.224609   3.369141   
748   6.298828   5.468750  10.205078  12.744141   8.105469   6.250000   
749   1.025391   0.097656   2.001953   2.832031   0.244141  -0.537109   

        EEG021     EEG022  
0     9.570312  15.771484  
1    -8.300781  -2.392578  
2   -29.931641 -25.537109  
3   -10.302734  -8.496094  
4   -12.011719 -12.402344  
..         ...        ...  
745  10.498047   9.375000  
746  20.507812  17.773438  
747   6.396484   2.734375  
748   9.667969   5.371094  
749   1.904297  -2.441406  

[750 rows x 22 columns]

## Grab indices from each trial which belong label 1 and 2

In [26]:
# Grab index from each trial that has label 1 and 2
# From run 04
idx_l04 = np.argwhere(y04==1).flatten() # Array containing trial classified as left
idx_r04 = np.argwhere(y04==2).flatten() # Array containing trial classified as left

# From run 05
idx_l05 = np.argwhere(y05==1).flatten() # Array containing trial classified as left
idx_r05 = np.argwhere(y05==2).flatten() # Array containing trial classified as left

# From run 06
idx_l06 = np.argwhere(y06==1).flatten() # Array containing trial classified as left
idx_r06 = np.argwhere(y06==2).flatten() # Array containing trial classified as left

# From run 07
idx_l07 = np.argwhere(y07==1).flatten() # Array containing trial classified as left
idx_r07 = np.argwhere(y07==2).flatten() # Array containing trial classified as left

# From run 08
idx_l08 = np.argwhere(y04==1).flatten() # Array containing trial classified as left
idx_r08 = np.argwhere(y04==2).flatten() # Array containing trial classified as left

# From run 09
idx_l09 = np.argwhere(y09==1).flatten() # Array containing trial classified as left
idx_r09 = np.argwhere(y09==2).flatten() # Array containing trial classified as left

In [27]:
# idx array will look like this
print('idx array is: ', idx_l04)

idx array is:  [ 0  3  5 10 13 19 22 23 26 30 32 35]


## Take 12 trials that belong to left & right class of each run

    E denotes matrix of sample x electrodes x trial
                        751    x      22    x 12

In [28]:
# Creating matrix of left class from all run
El04 = run04[idx_l04, :, :] # Run 4 left class
El05 = run05[idx_l05, :, :] # Run 5 left class
El06 = run06[idx_l06, :, :] # Run 6 left class
El07 = run07[idx_l07, :, :] # Run 7 left class
El08 = run08[idx_l08, :, :] # Run 8 left class
El09 = run09[idx_l09, :, :] # Run 9 left class

In [29]:
# Creating matrix of right class from all run
Er04 = run04[idx_r04, :, :] # Run 4 right class
Er05 = run05[idx_r05, :, :] # Run 5 right class
Er06 = run06[idx_r06, :, :] # Run 6 right class
Er07 = run07[idx_r07, :, :] # Run 7 right class
Er08 = run08[idx_r08, :, :] # Run 8 right class
Er09 = run09[idx_r09, :, :] # Run 9 right class

In [30]:
# Shape of each El and Er are
print('Shape of each El0x:',El04.shape,
      'Shape of each Er0x:',Er05.shape)

Shape of each El0x: (12, 750, 22) Shape of each Er0x: (12, 750, 22)


In [31]:
# Create E_right and E_left consist of right and left classes from all runs
E_left = np.concatenate((El04, El05, El06, El07, El08, El09), axis=0)
E_right = np.concatenate((Er04, Er05, Er06, Er07, Er08, Er09), axis=0)

In [32]:
# E_left and E_right should have dimension of 72 x 750 x 25
print('One run has 12 left and right each, there are 6 runs \nThus, dimension of E_left and E_right should be 72, 750, 25:')
print(E_left.shape, E_right.shape)

One run has 12 left and right each, there are 6 runs 
Thus, dimension of E_left and E_right should be 72, 750, 25:
(72, 750, 22) (72, 750, 22)


In [33]:
pd.DataFrame(E_right[34, :, :], columns=Xcol)

EEG01      EEG02      EEG03      EEG04      EEG05      EEG06  \
0    33.007812  21.435547  17.773438  15.869141  14.453125  16.748047   
1    38.623047  29.589844  24.462891  22.509766  21.435547  23.632812   
2    30.322266  23.388672  15.771484  13.281250  14.257812  20.507812   
3    42.138672  37.255859  28.369141  25.732422  28.857422  39.208984   
4    45.312500  31.396484  31.054688  25.634766  33.642578  37.109375   
..         ...        ...        ...        ...        ...        ...   
745   5.615234  10.058594  13.134766  10.937500  16.113281  19.580078   
746 -11.474609  -3.955078  -3.125000  -2.001953  -1.611328  -0.341797   
747  -9.130859  -1.171875   1.416016  -2.441406  -1.953125  -8.398438   
748  -6.445312  -1.855469   1.562500   3.417969   0.488281  -3.564453   
749  -9.667969  -6.250000  -0.781250  -3.857422  -3.369141 -12.255859   

         EEG07      EEG08      EEG09     EEG010  ...     EEG013     EEG014  \
0    17.675781  18.798828   9.619141   5.468750  ...   9.765625  14.843750   
1    22.558594  26.464844  15.917969  13.085938  ...  18.603516  22.363281   
2    14.013672  17.968750   7.128906   4.052734  ...  15.527344  12.451172   
3    24.902344  29.736328  20.068359  16.552734  ...  28.710938  22.167969   
4    25.976562  26.904297  22.949219  18.212891  ...  32.666016  22.558594   
..         ...        ...        ...        ...  ...        ...        ...   
745  13.525391  17.333984  20.117188  17.285156  ...  14.746094  20.361328   
746  -2.587891   4.931641   4.443359   4.687500  ...  -0.292969   7.373047   
747   3.564453   6.152344   9.130859   3.271484  ...  -1.318359   8.837891   
748  -1.318359   8.105469  10.107422   9.960938  ... -11.523438  12.939453   
749  -4.785156   0.585938   5.957031   2.685547  ...  -9.472656   6.103516   

        EEG015     EEG016     EEG017     EEG018     EEG019     EEG020  \
0     9.521484   5.371094   4.101562   3.710938   9.863281   6.591797   
1    16.357422  13.378906  13.330078  13.623047  15.332031  13.964844   
2     8.056641   5.371094   7.324219   9.912109   5.273438   5.126953   
3    18.896484  17.285156  22.363281  26.220703  18.603516  18.359375   
4    22.949219  19.042969  24.560547  28.613281  17.919922  18.994141   
..         ...        ...        ...        ...        ...        ...   
745  23.046875  22.265625  19.433594  16.162109  19.580078  19.384766   
746   7.812500   8.642578   3.515625  -0.732422   4.931641   4.931641   
747  11.376953   7.031250   2.441406  -2.392578   8.203125   5.566406   
748  12.744141  14.062500   8.056641   2.587891  13.330078  11.523438   
749   9.521484   6.201172   1.611328  -5.224609   7.324219   4.296875   

        EEG021     EEG022  
0     4.785156   7.861328  
1    12.402344  14.550781  
2     6.201172   5.761719  
3    20.068359  17.919922  
4    21.142578  18.164062  
..         ...        ...  
745  19.189453  19.726562  
746   3.759766   4.589844  
747   4.345703   6.591797  
748   9.228516  12.988281  
749   1.123047   4.443359  

[750 rows x 22 columns]

## Perform CAR(common average reference) to dataset

In [34]:
print('Perform CAR in each class, left and right. Executing...')
# CAR value of left class
avgleft = np.mean(E_left, axis=2)[:, :, np.newaxis]
CAR_left = E_left - avgleft;

# CAR value of right class
avgright = np.mean(E_right, axis=2)[:, :, np.newaxis]
CAR_right = E_right - avgright;

Perform CAR in each class, left and right. Executing...


In [35]:
pd.DataFrame(CAR_left[1, :, :], columns=Xcol)

EEG01     EEG02     EEG03     EEG04     EEG05     EEG06     EEG07  \
0    5.013761 -0.894442 -3.482333 -4.117099 -3.433505  2.035245  4.183683   
1    0.952148 -2.465820 -5.932617 -4.125977 -6.176758  1.635742  1.391602   
2   -2.195046 -6.247781 -6.296609 -7.224343 -5.320046 -1.120827  2.883079   
3   -2.763228 -5.155806 -6.230025 -6.815962 -4.472212 -2.470259  4.121538   
4   -4.833984 -1.513672 -6.054688 -4.296875 -6.152344 -1.806641  2.880859   
..        ...       ...       ...       ...       ...       ...       ...   
745  3.080611  1.127486 -3.608842 -1.411577 -1.899858  2.885298  2.152876   
746  4.336825  0.625888 -1.571378 -4.208097 -0.838956  0.332919  3.653232   
747  3.679865  0.799006 -0.324041 -2.033026  2.068537  4.949396  2.166193   
748  0.361772  1.435991 -1.786665 -0.370650 -1.591353 -1.591353  3.779741   
749  1.149680 -2.658913 -1.877663 -1.389382  0.612571  3.005149 -0.022195   

        EEG08     EEG09    EEG010  ...     EEG013    EEG014    EEG015  \
0   -5.874911 -2.749911 -5.777255  ...  11.410245  0.863370 -0.845614   
1   -4.907227 -3.344727 -3.881836  ...   7.153320  1.586914 -0.317383   
2   -5.368874 -1.755593 -4.978249  ...   9.865501  2.541282  1.613548   
3   -2.616744  0.410600 -3.251509  ...  10.810991  3.486772  2.900835   
4    2.880859  1.025391 -0.878906  ... -10.644531  6.298828  1.562500   
..        ...       ...       ...  ...        ...       ...       ...   
745  2.592330 -4.683061 -5.561967  ...   1.273970  1.859908 -0.483842   
746 -0.350675 -2.499112 -7.626065  ...   5.313388 -1.131925  0.772372   
747 -0.519354 -2.716619 -5.988104  ...   5.535334 -2.179510  0.310724   
748  3.340288 -3.495650 -2.470259  ...   7.246538  3.047319 -0.224165   
749 -0.266335 -2.512429 -3.684304  ...   9.450462  0.612571 -0.119851   

       EEG016    EEG017    EEG018    EEG019    EEG020    EEG021    EEG022  
0   -3.287021 -2.798739  1.791104 -1.919833  0.668058  2.181729  7.455167  
1   -0.366211 -0.268555  2.807617  0.756836  2.514648  4.418945  7.885742  
2    0.148704  0.832298  4.494407  0.392844  3.127219  4.543235  7.570579  
3    0.557085  0.947710  3.877397 -2.958540  1.191850  2.559038  1.094194  
4    3.417969  2.539062  4.833984 -1.123047  2.832031  4.541016  2.734375  
..        ...       ...       ...       ...       ...       ...       ...  
745 -1.802202 -0.679155  1.225142 -0.044389  2.104048  2.494673  5.131392  
746 -4.061612 -0.399503  1.748935  0.625888  1.504794  2.237216  5.996982  
747 -4.181463 -0.519354  0.945490 -2.081854  0.750178 -0.324041  2.556818  
748 -0.517134 -2.128462 -0.663619 -1.640181  0.312944 -1.493697  2.119585  
749 -1.535866 -0.803445  1.247337 -0.852273  0.417259 -1.877663  0.759055  

[750 rows x 22 columns]

## Divide dataset into training data and test data

In [36]:
# First transform the dimension of each sheet of CAR array to N x T
CAR_left = np.transpose(CAR_left, (0, 2, 1))
CAR_right = np.transpose(CAR_right, (0, 2, 1))

In [37]:
# Check dimension of shape of CAR_left and CAR_right
print('Transform CAR_left and CAR_right dimension to 72 x 22 x 750\n')
print('CAR_left now has dimension of: ', CAR_left.shape)
print('CAR_right now has dimension of: ', CAR_right.shape)

Transform CAR_left and CAR_right dimension to 72 x 22 x 750

CAR_left now has dimension of:  (72, 22, 750)
CAR_right now has dimension of:  (72, 22, 750)


In [38]:
# Take 54 data of each left and right data as training data
ntrain = 54
CAR_left_tr = CAR_left[:ntrain, :, :]
CAR_right_tr = CAR_right[:ntrain, :, :]
print('Take 54 data of each left and right data as training data\n')
print('CAR_left_tr has dimension of: ', CAR_left_tr.shape)
print('CAR_right_tr has dimension of: ', CAR_right_tr.shape)

Take 54 data of each left and right data as training data

CAR_left_tr has dimension of:  (54, 22, 750)
CAR_right_tr has dimension of:  (54, 22, 750)


In [39]:
# Take 18 data of each left and right data as train data
ntest = 18
CAR_left_te = CAR_left[:ntest, :, :]
CAR_right_te = CAR_right[:ntest, :, :]
print('Take 18 data of each left and right data as train data\n')
print('CAR_left_te has dimension of: ', CAR_left_te.shape)
print('CAR_right_te has dimension of: ', CAR_right_te.shape)

Take 18 data of each left and right data as train data

CAR_left_te has dimension of:  (18, 22, 750)
CAR_right_te has dimension of:  (18, 22, 750)


## Processing Training Data

### Calculate spatial covariance of each trial 
Calculating spatial covariance of each trial and composite variance

In [40]:
print('Compute covariance of CAR_left...\n')
Cov_left_tr = np.zeros((ntrain, nel, nel))
Cov_right_tr = np.zeros((ntrain, nel, nel))

for i in range(ntrain):
    Cov_left_tr[i, :, :] = (CAR_left_tr[i, :, :]@CAR_left_tr[i, :, :].T)/np.trace(CAR_left_tr[i, :, :]@CAR_left_tr[i, :, :].T)

for i in range(ntrain):
    Cov_right_tr[i, :, :] = (CAR_right_tr[i, :, :]@CAR_right_tr[i, :, :].T)/np.trace(CAR_right_tr[i, :, :]@CAR_right_tr[i, :, :].T)

print('Cov_left_tr has dimension of: ', Cov_left_tr.shape)
print('Cov_right_tr has dimension of: ', Cov_right_tr.shape)

Compute covariance of CAR_left...

Cov_left_tr has dimension of:  (54, 22, 22)
Cov_right_tr has dimension of:  (54, 22, 22)


### Compute average covariance left and right class


In [41]:
print('Compute covariance of left and right class for training...\n')
avgCov_l_tr = np.sum(Cov_left_tr, axis=0)/Cov_left_tr.shape[0]
avgCov_r_tr = np.sum(Cov_right_tr, axis=0)/Cov_right_tr.shape[0]
print('Cov_left_tr has dimension of: ', avgCov_l_tr.shape)
print('Cov_right_tr has dimension of: ', avgCov_r_tr.shape)

Compute covariance of left and right class for training...

Cov_left_tr has dimension of:  (22, 22)
Cov_right_tr has dimension of:  (22, 22)


In [42]:
# Composite spatial covariance
print('Calculating composite covariance...\n')
avgCov_c_tr = avgCov_l_tr + avgCov_r_tr
print('Size of avgCov_c_tr = ', avgCov_c_tr.shape)

Calculating composite covariance...

Size of avgCov_c_tr =  (22, 22)


In [43]:
# pd.DataFrame(avgCov_c_tr)

### Decompose the covariance matrix

In [45]:
avgCov_c_tr.shape

(22, 22)

In [61]:
# Try using np.linalg eigenvalue
# λ, V = np.linalg.eig(avgCov_c_tr)
λ, V = np.linalg.eig(avgCov_c_tr)

In [62]:
# Sort them in descending order, default of idx_des is to sort in ascending order
λ = np.sort(λ)[::-1]
idx_des = np.argsort(λ)[::-1]

In [63]:
λ

array([0.9625, 0.4365, 0.1911, 0.1208, 0.0605, 0.0422, 0.04  , 0.0342,
       0.0248, 0.0194, 0.0133, 0.0098, 0.0088, 0.0069, 0.0057, 0.0047,
       0.0045, 0.0041, 0.0037, 0.0034, 0.0031, 0.    ])

In [ ]:
# Sort eigenvector in descending order as well
# V = V[:, idx_des]

### White Transformation Matrix P & Spatial Matrix S
Construct whiten transformation matrix and transform the covariance matrix. <br>
First, construct the whiten transformation matrix P and spatial coefficient matrix S.<b>


In [132]:
# Computing White Transformation Matrix P
λ_sqr = 1/np.sqrt(λ)
P = np.diag(λ_sqr)@(V.T)

In [65]:
P.shape

(22, 22)

In [67]:
df(P)

0             1             2             3             4   \
0        0.412891  2.314109e-01  2.542034e-01  2.844219e-01  2.456216e-01   
1       -0.066304  3.830195e-01  2.084008e-01 -1.442536e-02 -2.173419e-01   
2        0.212764 -2.563908e-01  2.402536e-01  5.847713e-01  3.044013e-01   
3       -1.393061 -2.921054e-01 -2.885574e-01 -9.140654e-02 -2.533220e-01   
4        0.646398 -1.455777e+00  6.930816e-01 -6.049079e-01  6.264041e-01   
5       -0.144599 -1.796495e+00 -5.827657e-01  2.888033e-01  1.080419e+00   
6        0.666885  1.148815e+00  1.189719e+00 -4.369947e-01 -7.437417e-01   
7        2.876691 -8.394016e-01 -1.152430e+00 -1.449160e+00 -3.699912e-01   
8        1.615874  2.222728e-01 -9.009988e-01  1.567554e+00 -1.720080e+00   
9       -0.738718  3.255342e+00  6.623335e-01 -1.447334e+00 -2.650835e-01   
10      -1.613463  1.617950e+00  7.758586e-01 -2.434196e+00  2.482894e-01   
11       2.154729  2.154729e+00  2.154729e+00  2.154729e+00  2.154729e+00   
12      -2.273607 -6.575319e-01  1.373611e-01  3.835814e+00  8.746489e-01   
13       2.537266  1.759073e-01 -4.634983e+00 -2.046790e+00 -4.057835e+00   
14       1.461777  2.531971e+00 -4.283304e+00 -2.947910e+00  1.119091e+00   
15      -0.791395  4.436150e+00 -6.900977e+00  3.998370e+00  3.219583e+00   
16       0.107371 -7.366657e-01 -1.792099e+00  6.271088e+00 -6.564324e+00   
17       0.549546 -1.050387e-03  1.041188e+00 -2.876632e+00  2.295685e+00   
18      -0.585189  3.849792e+00  1.563189e+00 -5.756683e-01 -3.229762e+00   
19      -0.666806  2.717295e+00 -3.891838e+00 -1.111682e-01  6.224750e+00   
20      -0.077560  1.640361e+00 -1.849530e+00  2.988508e+00 -2.320284e+00   
21 -118891.428757  1.558106e+07 -5.334806e+07 -1.559167e+06  5.144870e+07   

              5             6             7             8             9   ...  \
0   2.175618e-01  6.257435e-02  4.163831e-02  5.708098e-02  7.908806e-02  ...   
1  -3.935064e-01  4.954825e-01  5.446960e-01  2.919234e-01  1.623667e-02  ...   
2  -1.361246e-01 -1.209131e+00 -4.154162e-01  2.468204e-01  6.883971e-01  ...   
3  -2.002958e-01 -2.271961e-01  5.345420e-01  4.648529e-01  7.990895e-01  ...   
4  -1.726014e+00  1.313321e+00 -1.164983e+00  1.175591e+00 -1.515101e-01  ...   
5   1.302264e+00 -4.537466e-01 -3.142465e-01 -1.305885e-01  3.939297e-01  ...   
6  -1.371087e+00 -3.197881e+00  7.995315e-01  1.081318e+00 -7.522987e-01  ...   
7   8.203369e-01 -3.240089e-01  2.522603e-01 -6.389843e-01 -1.824340e+00  ...   
8  -1.637471e+00  8.576270e-01 -8.571790e-01 -1.666655e+00  1.853713e+00  ...   
9  -9.473384e-02  4.087297e-01 -1.391164e+00 -1.446962e+00  1.991193e-01  ...   
10  3.907962e+00 -1.791703e-02 -5.915919e-01  1.262190e+00 -1.604755e+00  ...   
11  2.154729e+00  2.154729e+00  2.154729e+00  2.154729e+00  2.154729e+00  ...   
12  2.007770e+00  5.635302e-01 -1.012637e+00  1.379954e+00 -9.052648e-01  ...   
13  2.849723e+00  2.621909e-01 -1.525748e-01  6.937137e+00  3.916065e+00  ...   
14 -6.794644e-01 -7.713544e-01  1.092482e+00 -2.141279e+00  3.031054e+00  ...   
15 -2.309153e+00 -5.338383e-01 -1.680982e+00 -6.094379e-01 -3.259400e+00  ...   
16  6.799153e-01  4.627806e-01  1.974141e+00 -6.061596e-01 -2.892535e+00  ...   
17 -3.037035e+00  3.161588e-01 -1.138671e+00  4.284774e-01  3.162634e+00  ...   
18  2.118170e+00  3.151012e-01 -1.041437e+01 -1.024686e+00  3.474268e+00  ...   
19 -2.647716e+00 -3.756404e-02 -2.123941e+00  4.682278e+00 -4.096536e+00  ...   
20 -1.769239e+00  5.788733e-01 -5.035995e+00  6.789821e+00 -4.418049e+00  ...   
21 -1.048760e+07 -2.070243e+06  2.985678e+07 -3.022297e+06  4.059446e+07  ...   

               12            13            14            15            16  \
0        0.035854 -1.309025e-01 -1.261053e-01 -1.377328e-01 -1.321002e-01   
1       -0.626860  4.808721e-01  2.689652e-01  1.471167e-02 -2.261287e-01   
2       -1.286510 -2.647874e-01  1.807744e-01  5.092403e-01  2.769547e-01   
3        0.351028  5.051116e-01  4.398015e-01  7.543086e-01  4.352603e-

In [74]:
# Use this whitening matrix transform Sl and Sr as follows
# Sl = P Cl P'
S_left = P@avgCov_l_tr@P.T
# Sr = P Cr P'
S_right = P@avgCov_r_tr@P.T

In [77]:
S_left.shape, S_right.shape

((22, 22), (22, 22))

### Compute projection matrix W

In [96]:
# Find Ul (eigenvector of both S_left and S_right)
# Decompose Sl and Sr
Ul, Ll, Vl = np.linalg.svd(S_left)
Ur, Lr, Vr = np.linalg.svd(S_right)

In [89]:
# Sort in ascending order
Ll.sort()
Ll

array([5.3787e-16, 3.6196e-01, 4.1351e-01, 4.2676e-01, 4.6043e-01,
       4.8596e-01, 4.9192e-01, 5.0098e-01, 5.1890e-01, 5.1950e-01,
       5.2966e-01, 5.4004e-01, 5.4273e-01, 5.5664e-01, 5.6637e-01,
       6.2258e-01, 6.4066e-01, 6.4783e-01, 6.7212e-01, 6.9607e-01,
       7.7747e-01, 5.3446e+13])

In [93]:
# Sort in descending order
Lr = np.sort(Lr)[::-1]
Lr

array([4.9066e+13, 7.2033e-01, 6.4134e-01, 6.2223e-01, 6.1332e-01,
       5.9194e-01, 5.7024e-01, 5.4410e-01, 5.3790e-01, 5.1584e-01,
       5.0692e-01, 4.9465e-01, 4.8128e-01, 4.7677e-01, 4.7152e-01,
       4.6603e-01, 4.5451e-01, 4.4820e-01, 4.3021e-01, 3.6733e-01,
       3.2224e-01, 9.9061e-16])

In [91]:
# Validating that both eigenvectors adds up to identity matrix
Ll_diag = np.diag(Ll)
Lr_diag = np.diag(Lr)
df(Lr_diag + Ll_diag)

0         1         2         3         4         5         6   \
0   1.528474e-15  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1   0.000000e+00  0.684193  0.000000  0.000000  0.000000  0.000000  0.000000   
2   0.000000e+00  0.000000  0.780839  0.000000  0.000000  0.000000  0.000000   
3   0.000000e+00  0.000000  0.000000  0.856973  0.000000  0.000000  0.000000   
4   0.000000e+00  0.000000  0.000000  0.000000  0.908627  0.000000  0.000000   
5   0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.940469  0.000000   
6   0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000  0.957952   
7   0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8   0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
9   0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
10  0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
11  0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
12  0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
13  0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
14  0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
15  0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
16  0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
17  0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
18  0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
19  0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
20  0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
21  0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

          7         8         9   ...        12        13        14        15  \
0   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
1   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
2   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
3   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
4   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
5   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
6   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
7   0.972497  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
8   0.000000  0.995674  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
9   0.000000  0.000000  1.000784  ...  0.000000  0.000000  0.000000  0.000000   
10  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
11  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
12  0.000000  0.000000  0.000000  ...  1.058574  0.000000  0.000000  0.000000   
13  0.000000  0.000000  0.000000  ...  0.000000  1.094536  0.000000  0.000000   
14  0.000000  0.000000  0.000000  ...  0.000000  0.000000  1.110477  0.000000   
15  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  1.192824   
16  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
17  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
18  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
19  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
20  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
21  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   

        16        17        18        19        20            21  
0   0.0000  0.000000  0.000000  0.000000  0.000000  0.000000e+00  
1   0.0000  0.000000  0.000000  0.000000  0.000000  0.000000e+00  
2   0.0000  0.000000  0.000000  0.000000  0.000000  0.000000e+00  
3   0.0000  0.000000  0.000000  0.000000 

In [94]:
# Projection matrix W
W = (Ul@P).T

In [133]:
W.shape

(22, 22)

### Feature Vector for Training Data

In [121]:
# Let's follow the procedure in the paper and set m = 2
# So 2m = 4
# So take the first m of first and last row of matrix
# And remove the rest of matrix row
m = 2
x, y = W.shape
W_new = np.delete(W, np.s_[m+1:x-m+1], 0)

In [122]:
W_new.shape

(4, 22)

So now we have matrix W with dimension of $2m * N$

Apply this matrix to original EEG trial signals E with the dim $N*T$ to obtain Z with dim of $2m * T$

Now calculate Z

        Z = W * E
    2m x N = 2m x N * N x T 

In [165]:
# Preparing necessary variables
ntrial = 72

# Tranposing E to appropriate dimension
E_left = np.transpose(E_left, (0, 2, 1))
E_right= np.transpose(E_right, (0, 2, 1))

# New zeros array for Z
Z_left = np.zeros((E_left.shape[0], W_new.shape[0], E_left.shape[2]))
Z_right = np.zeros((E_right.shape[0], W_new.shape[0], E_right.shape[2]))

In [166]:
# For left class
for i in range(Z_left.shape[0]):
    Z_left[i] = W_new@E_left[i]

# For right class
for i in range(Z_left.shape[0]):
    Z_right[i] = W_new@E_right[i]

In [ ]:
# ===== Feature Vector =====
var = Z_left[i], ddof=1, axis=1

In [204]:
var = np.var(Z_left[0], ddof=1, axis=1)

In [205]:
var.shape

(4,)

In [172]:
Z_left.shape

(72, 4, 750)

In [170]:
test = np.var(Z_left, axis=2)

In [171]:
test.shape

(72, 4)

In [173]:
a = np.random.randint(2, 5, 24).reshape(2, 4, 3)

In [174]:
a

array([[[4, 4, 2],
        [2, 3, 3],
        [3, 2, 4],
        [3, 4, 3]],

       [[2, 3, 4],
        [4, 4, 4],
        [2, 4, 3],
        [2, 3, 3]]])

In [177]:
np.var(a[0], axis=1)/np.sum(a[0], axis=1)

array([0.0889, 0.0278, 0.0741, 0.0222])

In [195]:
a

array([[[4, 4, 2],
        [2, 3, 3],
        [3, 2, 4],
        [3, 4, 3]],

       [[2, 3, 4],
        [4, 4, 4],
        [2, 4, 3],
        [2, 3, 3]]])

In [196]:
nah = np.var(a[0], ddof=1, axis=1)

In [197]:
nah

array([1.3333, 0.3333, 1.    , 0.3333])

In [199]:
sumvar = np.sum(np.var(a[0], ddof=1, axis=1))

In [200]:
sumvar

3.0

In [201]:
nah/sumvar

array([0.4444, 0.1111, 0.3333, 0.1111])

In [191]:
a[0]

array([[4, 4, 2],
       [2, 3, 3],
       [3, 2, 4],
       [3, 4, 3]])

In [158]:
E_left = np.transpose(E_left, (0, 2, 1))

In [136]:
Z = np.zeros((E_left.shape[0], W_new.shape[0], E_left.shape[2]))

In [137]:
Z.shape

(72, 4, 750)

In [153]:
for i in range(Zl.shape[0]):
    Z[i] = W_new@E_left[i]

In [139]:
Z.shape

(72, 4, 750)

In [149]:
W_new@E_left[71]

array([[-7.3151e+05,  5.2248e+05,  1.2188e+05, ...,  1.1843e+06,
         1.1378e+06,  1.0391e+06],
       [ 9.5860e+07, -6.8471e+07, -1.5977e+07, ..., -1.5520e+08,
        -1.4912e+08, -1.3618e+08],
       [-3.2822e+08,  2.3444e+08,  5.4703e+07, ...,  5.3140e+08,
         5.1056e+08,  4.6627e+08],
       [-1.7316e+07,  1.2369e+07,  2.8860e+06, ...,  2.8035e+07,
         2.6936e+07,  2.4600e+07]])

In [156]:
df(Z[70])

0             1             2             3             4    \
0 -3.714887e+05 -2.437497e+05 -2.844340e+05 -1.857616e+06  1.816959e+06   
1  4.869075e+07  3.195328e+07  3.727886e+07  2.434540e+08 -2.381284e+08   
2 -1.667127e+08 -1.094052e+08 -1.276394e+08 -8.335635e+08  8.153292e+08   
3 -8.795389e+06 -5.771972e+06 -6.733941e+06 -4.397716e+07  4.301527e+07   

            5             6             7             8             9    ...  \
0  2.780495e+06  4.458167e+06  5.102575e+06  1.770523e+06  2.171049e+06  ...   
1 -3.644201e+08 -5.842895e+08 -6.687376e+08 -2.320420e+08 -2.845368e+08  ...   
2  1.247740e+09  2.000552e+09  2.289695e+09  7.944901e+08  9.742273e+08  ...   
3  6.582845e+07  1.055453e+08  1.207999e+08  4.191578e+07  5.139836e+07  ...   

            740           741           742           743           744  \
0 -7.779008e+05  4.179404e+05 -2.066571e+06 -6.037385e+05 -1.178476e+06   
1  1.019464e+08 -5.477713e+07  2.708426e+08  7.912258e+07  1.544412e+08   
2 -3.490547e+08  1.875518e+08 -9.273394e+08 -2.709082e+08 -5.287919e+08   
3 -1.841547e+07  9.894856e+06 -4.892466e+07 -1.429260e+07 -2.789803e+07   

            745           746           747           748           749  
0 -3.082487e+06 -2.751632e+06 -3.657194e+06 -2.072414e+06 -1.735715e+06  
1  4.039815e+08  3.606163e+08  4.793001e+08  2.716034e+08  2.274773e+08  
2 -1.383194e+09 -1.234716e+09 -1.641078e+09 -9.299443e+08 -7.788609e+08  
3 -7.297468e+07 -6.514124e+07 -8.658014e+07 -4.906208e+07 -4.109122e+07  

[4 rows x 750 columns]

In [127]:
E_left.shape

(72, 750, 22)

In [131]:
asd = np.transpose(E_left, (0, 2, 1))

In [120]:
x

22

In [119]:
test = np.random.randint(1, 5, 10).reshape(5,2)
test

array([[1, 4],
       [3, 4],
       [3, 1],
       [4, 2],
       [4, 1]])

In [115]:
test.shape

(5, 2)

In [116]:
np.delete(test, np.s_[2:4], 0)

array([[2, 3],
       [2, 1],
       [4, 2]])

In [ ]:
idx_des

In [ ]:
np.sort(t)

In [ ]:
t

In [ ]:
asc = np.argsort(t)
asc

In [ ]:
des = np.argsort(t)[::-1]
des

In [ ]:
a

In [ ]:
eigenval

In [ ]:
eigenvec

In [ ]:
U, S, V = np.linalg.svd(a)

In [ ]:
pd.DataFrame(U)

In [ ]:
U@np.diag(S)@V

In [ ]:
pd.DataFrame(V)

In [ ]:
a = np.array([[5, 5, 2], [5, 4, 3], [1, 1, 5]])
a

In [ ]:
# 3D array ex
a = np.arange(12).reshape(2, 3, 2)
b = a*2-7

In [ ]:
test = np.sum(a, axis=0)

In [ ]:
test

In [ ]:
ans = (CAR_left_tr[i, :, :]@CAR_left_tr[i, :, :].T)/np.trace(CAR_left_tr[i, :, :]@CAR_left_tr[i, :, :].T)

In [ ]:
a = np.arange(1, 10).reshape(3, 3, order='F')

In [ ]:
a

In [ ]:
np.trace(a)